name: build-and-attest
on: [push]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  call-build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      path: "output.txt"

      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
